package com.dao;

import com.conexion.Conexion;
import com.modelo.faturaConsumidorFinal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author josue
 */
public class DaoFaturaConsumidorFinal extends Conexion {

    public List<faturaConsumidorFinal> getFaturaConsumidorFinal() throws Exception {
        ResultSet rs;
        List<faturaConsumidorFinal> lst = new ArrayList();
        try {
            this.conectar();
            String sql = "SELECT * FROM faturaConsumidorFinal";
            PreparedStatement pst = (PreparedStatement) this.getCon().prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                faturaConsumidorFinal fatConsuFinal = new faturaConsumidorFinal();
                fatConsuFinal.setIdFacturaConsumidorFinal(rs.getInt("idfaturaConsumidorFinal"));
                fatConsuFinal.setNit(rs.getString("nit"));
                fatConsuFinal.setNrc(rs.getString("nrc"));
                fatConsuFinal.setIdDepartamentoEmisor(rs.getInt("idDepartamentoEmisor"));
                fatConsuFinal.setMunicipio(rs.getString("idMunicipioEmisor"));
                fatConsuFinal.setDireccionEmisor(rs.getString("direccionEmisor"));
                fatConsuFinal.setFechaEnvio(rs.getString("fechaEnvio"));
                fatConsuFinal.setFechaEmision(rs.getString("fechaEmision"));
                fatConsuFinal.setTerminal(rs.getString("terminal"));
                fatConsuFinal.setNumFactura(rs.getInt("numFactura"));
                fatConsuFinal.setCorrelativoInterno(rs.getInt("correlativoInterno"));
                fatConsuFinal.setNumeroTransaccion(rs.getInt("numeroTransaccion"));
                fatConsuFinal.setCodigoUsuario(rs.getInt("codigoUsuario"));
                fatConsuFinal.setNombreUsuario(rs.getString("nombreUsuario"));
                fatConsuFinal.setCorreoUsuario(rs.getString("correoUsuario"));
                fatConsuFinal.setCajaSuc(rs.getString("cajaSuc"));
                fatConsuFinal.setTipoDocumento(rs.getString("tipoDocumento"));
                fatConsuFinal.setPdv(rs.getString("pdv"));
                fatConsuFinal.setNitCliente(rs.getString("nitCliente"));
                fatConsuFinal.setDuiCliente(rs.getString("duiCliente"));
                fatConsuFinal.setNrcCliente(rs.getString("nrcCliente"));
                fatConsuFinal.setCodigoCliente(rs.getInt("codigoCliente"));
                fatConsuFinal.setNombreCliente(rs.getString("nombreCliente"));
                fatConsuFinal.setDireccionCliente(rs.getString("direccionCliente"));
                fatConsuFinal.setDepartamento(rs.getString("departamento"));
                fatConsuFinal.setMunicipio(rs.getString("municipio"));
                fatConsuFinal.setTelefono(rs.getString("telefono"));
                fatConsuFinal.setEmail(rs.getString("email"));
                fatConsuFinal.setSms(rs.getString("sms"));
                fatConsuFinal.setWhatsapp(rs.getString("whatsapp"));
                fatConsuFinal.setIdDepartamentoReceptor(rs.getInt("idDepartamentoReceptor"));
                fatConsuFinal.setIdMunicipioReceptor(rs.getInt("idMunicipioReceptor"));
                fatConsuFinal.setCodigoActividadEconomica(rs.getInt("codigoActividadEconomica"));
                fatConsuFinal.setTipoCatContribuyente(rs.getString("tipoCatContribuyente"));
                fatConsuFinal.setGiro(rs.getString("giro"));
                fatConsuFinal.setCodicionPago(rs.getInt("codicionPago"));
                fatConsuFinal.setCCFAnterior(rs.getString("CCFAnterior"));
                fatConsuFinal.setVtaACuentaDe(rs.getString("vtaACuentaDe"));
                fatConsuFinal.setNotaRemision(rs.getString("notaRemision"));
                fatConsuFinal.setNoFecha(rs.getString("noFecha"));
                fatConsuFinal.setSaldoCapital(rs.getDouble("saldoCapital"));
                fatConsuFinal.setDescripcion(rs.getString("descripcion"));
                fatConsuFinal.setPrecioUnitario(rs.getDouble("precioUnitario"));
                fatConsuFinal.setVentasNoSujetas(rs.getDouble("ventasNoSujetas"));
                fatConsuFinal.setIvaItem(rs.getDouble("ivaItem"));
                fatConsuFinal.setDelAl(rs.getDouble("delAl"));
                fatConsuFinal.setExportaciones(rs.getInt("exportaciones"));
                fatConsuFinal.setNumDocRel(rs.getInt("numDocRel"));
                fatConsuFinal.setCodTributo(rs.getInt("codTributo"));
                fatConsuFinal.setTributos(rs.getInt("tributos"));
                fatConsuFinal.setUniMedidaCodigo(rs.getInt("uniMedidaCodigo"));
                fatConsuFinal.setVentasExentas(rs.getDouble("ventasExentas"));
                fatConsuFinal.setFecha(rs.getString("fecha"));
                fatConsuFinal.setTipoItem(rs.getInt("tipoItem"));
                fatConsuFinal.setTipoDteRel(rs.getInt("tipoDteRel"));
                fatConsuFinal.setCodigoRetencionMH(rs.getInt("codigoRetencionMH"));
                fatConsuFinal.setCantidad(rs.getInt("cantidad"));
                fatConsuFinal.setVentasGravadas(rs.getInt("ventasGravadas"));
                fatConsuFinal.setIvaRetenido(rs.getDouble("ivaRetenido"));
                fatConsuFinal.setDescuento(rs.getDouble("descuento"));
                fatConsuFinal.setDescuentoItem(rs.getInt("descuentoItem"));
                fatConsuFinal.setOtroMonNoAfec(rs.getInt("otroMonNoAfec"));
                fatConsuFinal.setMontoLetras(rs.getString("montoLetras"));
                fatConsuFinal.setSumas(rs.getDouble("sumas"));
                fatConsuFinal.setSubTotalVentasExentas(rs.getDouble("subTotalVentasExentas"));
                fatConsuFinal.setSubTotalVentasNoSujetas(rs.getDouble("subTotalVentasNoSujetas"));
                fatConsuFinal.setSubTotalVentasGravadas(rs.getDouble("subTotalVentasGravadas"));
                fatConsuFinal.setVentasGravada(rs.getDouble("ventasGravada"));
                fatConsuFinal.setIva(rs.getDouble("iva"));
                fatConsuFinal.setRenta(rs.getDouble("renta"));
                fatConsuFinal.setImpuesto(rs.getDouble("impuesto"));
                fatConsuFinal.setVentasExenta(rs.getDouble("ventasExenta"));
                fatConsuFinal.setVentasNoSujeta(rs.getDouble("ventasNoSujeta"));
                fatConsuFinal.setCodigoTributo(rs.getDouble("codigoTributo"));
                fatConsuFinal.setCodigoTributos(rs.getInt("codigoTributos"));
                fatConsuFinal.setDescripcionTributo(rs.getString("descripcionTributo"));
                fatConsuFinal.setValorTributo(rs.getDouble("valorTributo"));
                fatConsuFinal.setDescuentos(rs.getDouble("descuentos"));
                fatConsuFinal.setAbonos(rs.getDouble("abonos"));
                fatConsuFinal.setCantidadTotal(rs.getInt("cantidadTotal"));
                fatConsuFinal.setVentaTotal(rs.getDouble("ventaTotal"));
                fatConsuFinal.setVentasGravadas13(rs.getDouble("ventasGravadas13"));
                fatConsuFinal.setVentasGravadas0(rs.getDouble("ventasGravadas0"));
                fatConsuFinal.setVentasNoGravadas(rs.getDouble("ventasNoGravadas"));
                fatConsuFinal.setIvaPercibido1(rs.getDouble("ivaPercibido1"));
                fatConsuFinal.setIvaPercibido2(rs.getDouble("ivaPercibido2"));
                fatConsuFinal.setIvaRetenido1(rs.getDouble("ivaRetenido1"));
                fatConsuFinal.setIvaRetenido13(rs.getDouble("ivaRetenido13"));
                fatConsuFinal.setMontGDescVentNoSujetas(rs.getDouble("montGDescVentNoSujetas"));
                fatConsuFinal.setMontGDescVentExentas(rs.getDouble("montGDescVentExentas"));
                fatConsuFinal.setMontGDescVentGrav(rs.getDouble("montGDescVentGrav"));
                fatConsuFinal.setTotOtroMonNoAfec(rs.getDouble("totOtroMonNoAfec"));
                fatConsuFinal.setTotalAPagar(rs.getDouble("totalAPagar"));
                fatConsuFinal.setSeguro(rs.getDouble("seguro"));
                fatConsuFinal.setFlete(rs.getDouble("flete"));
                fatConsuFinal.setContribucionSeguridad(rs.getDouble("contribucionSeguridad"));
                fatConsuFinal.setFovial(rs.getDouble("fovial"));
                fatConsuFinal.setCotrans(rs.getDouble("cotrans"));
                fatConsuFinal.setContribucionTurismo5(rs.getDouble("contribucionTurismo5"));
                fatConsuFinal.setContribucionTurismo7(rs.getDouble("contribucionTurismo7"));
                fatConsuFinal.setImpuestoEspecifico(rs.getDouble("impuestoEspecifico"));
                fatConsuFinal.setCesc(rs.getDouble("cesc"));
                fatConsuFinal.setCampo1(rs.getString("campo1"));
                fatConsuFinal.setCampo2(rs.getString("campo2"));
                fatConsuFinal.setCampo3(rs.getString("campo3"));
                fatConsuFinal.setCampo4(rs.getString("campo4"));
                fatConsuFinal.setCampoExtFE(rs.getString("campoExtFE"));
                fatConsuFinal.setTipoItemExpor(rs.getString("tipoItemExpor"));
                fatConsuFinal.setCodSucE(rs.getString("codSucE"));
                fatConsuFinal.setEmailE(rs.getString("emailE"));
                fatConsuFinal.setCodPais(rs.getString("codPais"));
                fatConsuFinal.setObservacionesDte(rs.getString("observacionesDte"));
                fatConsuFinal.setNombrePais(rs.getString("nombrePais"));
                fatConsuFinal.setFechaHoraGeneracion(rs.getString("fechaHoraGeneracion"));
                fatConsuFinal.setTipoPersona(rs.getString("tipoPersona"));
                fatConsuFinal.setNumControl(rs.getString("numControl"));
                fatConsuFinal.setCodGeneracion(rs.getString("codGeneracion"));
                fatConsuFinal.setTelsucE(rs.getString("telsucE"));
                fatConsuFinal.setSelloGeneracion(rs.getString("selloGeneracion"));
                fatConsuFinal.setFormatodocumento(rs.getString("formatodocumento"));
                fatConsuFinal.setResolucion(rs.getString("resolucion"));
                fatConsuFinal.setResInicio(rs.getString("resInicio"));
                fatConsuFinal.setResFin(rs.getString("resFin"));
                fatConsuFinal.setResFecha(rs.getString("resFecha"));
                fatConsuFinal.setSerie(rs.getString("serie"));
                fatConsuFinal.setOtrosDocIdent(rs.getString("otrosDocIdent"));
                fatConsuFinal.setOtrosDocDescri(rs.getString("otrosDocDescri"));
                fatConsuFinal.setVentCterNit(rs.getString("ventCterNit"));
                fatConsuFinal.setVentCterNombre(rs.getString("ventCterNombre"));
                fatConsuFinal.setDocRelTipo(rs.getString("docRelTipo"));
                fatConsuFinal.setDocRelNum(rs.getString("docRelNum"));
                fatConsuFinal.setDocRelFecha(rs.getString("docRelFecha"));
                fatConsuFinal.setFormaPago(rs.getString("formaPago"));
                fatConsuFinal.setPlazo(rs.getString("plazo"));
                fatConsuFinal.setNomConductor(rs.getString("nomConductor"));
                fatConsuFinal.setNumIdenConductor(rs.getString("numIdenConductor"));
                fatConsuFinal.setModTransp(rs.getString("modTransp"));
                fatConsuFinal.setNumIdTransp(rs.getString("numIdTransp"));
                fatConsuFinal.setResponsableEmisor(rs.getString("responsableEmisor"));
                fatConsuFinal.setNumDocEmisor(rs.getString("numDocEmisor"));
                fatConsuFinal.setResponsableReceptor(rs.getString("responsableReceptor"));
                fatConsuFinal.setNumDocReceptor(rs.getString("numDocReceptor"));
                fatConsuFinal.setMostrarTributo(rs.getString("mostrarTributo"));
                fatConsuFinal.setNumeroControl(rs.getString("numeroControl"));
                fatConsuFinal.setCodigoGeneracion(rs.getString("codigoGeneracion"));
                fatConsuFinal.setMotivoContin(rs.getString("motivoContin"));
                fatConsuFinal.setNombreComercialCl(rs.getString("nombreComercialCl"));
                fatConsuFinal.setCodContingencia(rs.getString("codContingencia"));
                fatConsuFinal.setModeloFacturacion(rs.getString("modeloFacturacion"));
                fatConsuFinal.setTipoTransmisión(rs.getString("tipoTransmisión"));
                fatConsuFinal.setfInicioContin(rs.getString("fInicioContin"));
                fatConsuFinal.setfFinContin(rs.getString("fFinContin"));
                fatConsuFinal.setHoraIniContin(rs.getString("horaIniContin"));
                fatConsuFinal.setHoraFinContin(rs.getString("horaFinContin"));
                fatConsuFinal.setEstado(rs.getInt("estado"));
                lst.add(fatConsuFinal);
            }
        } catch (Exception e) {
            throw e;
        } finally {
            this.desconectar();
        }
        return lst;
    }

    public void insertFaturaConsumidorFinal(faturaConsumidorFinal fatConsuFinal) throws Exception {
        try {
            this.conectar();
            String sql = "INSERT INTO faturaConsumidorFinal VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0);";
            PreparedStatement pst = this.getCon().prepareStatement(sql);
            pst.setString(1, fatConsuFinal.getNit());
            pst.setString(2, fatConsuFinal.getNrc());
            pst.setInt(3, fatConsuFinal.getIdDepartamentoEmisor());
            pst.setInt(4, fatConsuFinal.getIdMunicipioEmisor());
            pst.setString(5, fatConsuFinal.getDireccionEmisor());
            pst.setString(6, fatConsuFinal.getFechaEnvio());
            pst.setString(7, fatConsuFinal.getFechaEmision());
            pst.setString(8, fatConsuFinal.getTerminal());
            pst.setInt(9, fatConsuFinal.getNumFactura());
            pst.setInt(10, fatConsuFinal.getCorrelativoInterno());
            pst.setInt(11, fatConsuFinal.getNumeroTransaccion());
            pst.setInt(12, fatConsuFinal.getCodigoUsuario());
            pst.setString(13, fatConsuFinal.getNombreUsuario());
            pst.setString(14, fatConsuFinal.getCorreoUsuario());
            pst.setString(15, fatConsuFinal.getCajaSuc());
            pst.setString(16, fatConsuFinal.getTipoDocumento());
            pst.setString(17, fatConsuFinal.getPdv());
            pst.setString(18, fatConsuFinal.getNitCliente());
            pst.setString(19, fatConsuFinal.getDuiCliente());
            pst.setString(20, fatConsuFinal.getNrcCliente());
            pst.setInt(21, fatConsuFinal.getCodigoCliente());
            pst.setString(22, fatConsuFinal.getNombreCliente());
            pst.setString(23, fatConsuFinal.getDireccionCliente());
            pst.setString(24, fatConsuFinal.getDepartamento());
            pst.setString(25, fatConsuFinal.getMunicipio());
            pst.setString(26, fatConsuFinal.getTelefono());
            pst.setString(27, fatConsuFinal.getEmail());
            pst.setString(28, fatConsuFinal.getSms());
            pst.setString(29, fatConsuFinal.getWhatsapp());
            pst.setInt(30, fatConsuFinal.getIdDepartamentoReceptor());
            pst.setInt(31, fatConsuFinal.getIdMunicipioReceptor());
            pst.setInt(32, fatConsuFinal.getCodigoActividadEconomica());
            pst.setString(33, fatConsuFinal.getTipoCatContribuyente());
            pst.setString(34, fatConsuFinal.getGiro());
            pst.setInt(35, fatConsuFinal.getCodicionPago());
            pst.setString(36, fatConsuFinal.getCCFAnterior());
            pst.setString(37, fatConsuFinal.getVtaACuentaDe());
            pst.setString(38, fatConsuFinal.getNotaRemision());
            pst.setString(39, fatConsuFinal.getNoFecha());
            pst.setDouble(40, fatConsuFinal.getSaldoCapital());
            pst.setString(41, fatConsuFinal.getDescripcion());
            pst.setDouble(42, fatConsuFinal.getPrecioUnitario());
            pst.setDouble(43, fatConsuFinal.getVentasNoSujetas());
            pst.setDouble(44, fatConsuFinal.getIvaItem());
            pst.setDouble(45, fatConsuFinal.getDelAl());
            pst.setInt(46, fatConsuFinal.getExportaciones());
            pst.setInt(47, fatConsuFinal.getNumDocRel());
            pst.setInt(48, fatConsuFinal.getCodTributo());
            pst.setDouble(49, fatConsuFinal.getTributos());
            pst.setInt(50, fatConsuFinal.getUniMedidaCodigo());
            pst.setDouble(51, fatConsuFinal.getVentasExentas());
            pst.setString(52, fatConsuFinal.getFecha());
            pst.setInt(53, fatConsuFinal.getTipoItem());
            pst.setInt(54, fatConsuFinal.getTipoDteRel());
            pst.setInt(55, fatConsuFinal.getCodigoRetencionMH());
            pst.setInt(56, fatConsuFinal.getCantidad());
            pst.setInt(57, fatConsuFinal.getVentasGravadas());
            pst.setDouble(58, fatConsuFinal.getIvaRetenido());
            pst.setDouble(59, fatConsuFinal.getDescuento());
            pst.setInt(60, fatConsuFinal.getDescuentoItem());
            pst.setDouble(61, fatConsuFinal.getOtroMonNoAfec());
            pst.setString(62, fatConsuFinal.getMontoLetras());
            pst.setDouble(63, fatConsuFinal.getSumas());
            pst.setDouble(64, fatConsuFinal.getSubTotalVentasExentas());
            pst.setDouble(65, fatConsuFinal.getSubTotalVentasNoSujetas());
            pst.setDouble(66, fatConsuFinal.getSubTotalVentasGravadas());
            pst.setDouble(67, fatConsuFinal.getVentasGravada());
            pst.setDouble(68, fatConsuFinal.getIva());
            pst.setDouble(69, fatConsuFinal.getRenta());
            pst.setDouble(70, fatConsuFinal.getImpuesto());
            pst.setDouble(71, fatConsuFinal.getVentasExenta());
            pst.setDouble(72, fatConsuFinal.getVentasNoSujeta());
            pst.setDouble(73, fatConsuFinal.getCodigoTributo());
            pst.setInt(74, fatConsuFinal.getCodigoTributos());
            pst.setString(75, fatConsuFinal.getDescripcionTributo());
            pst.setDouble(76, fatConsuFinal.getValorTributo());
            pst.setDouble(77, fatConsuFinal.getDescuentos());
            pst.setDouble(78, fatConsuFinal.getAbonos());
            pst.setInt(79, fatConsuFinal.getCantidadTotal());
            pst.setDouble(80, fatConsuFinal.getVentaTotal());
            pst.setDouble(81, fatConsuFinal.getVentasGravadas13());
            pst.setDouble(82, fatConsuFinal.getVentasGravadas0());
            pst.setDouble(83, fatConsuFinal.getVentasNoGravadas());
            pst.setDouble(84, fatConsuFinal.getIvaPercibido1());
            pst.setDouble(85, fatConsuFinal.getIvaPercibido2());
            pst.setDouble(86, fatConsuFinal.getIvaRetenido1());
            pst.setDouble(87, fatConsuFinal.getIvaRetenido13());
            pst.setDouble(88, fatConsuFinal.getMontGDescVentNoSujetas());
            pst.setDouble(89, fatConsuFinal.getMontGDescVentExentas());
            pst.setDouble(90, fatConsuFinal.getMontGDescVentGrav());
            pst.setDouble(91, fatConsuFinal.getTotOtroMonNoAfec());
            pst.setDouble(92, fatConsuFinal.getTotalAPagar());
            pst.setDouble(93, fatConsuFinal.getSeguro());
            pst.setDouble(94, fatConsuFinal.getFlete());
            pst.setDouble(95, fatConsuFinal.getContribucionSeguridad());
            pst.setDouble(96, fatConsuFinal.getFovial());
            pst.setDouble(97, fatConsuFinal.getCotrans());
            pst.setDouble(98, fatConsuFinal.getContribucionTurismo5());
            pst.setDouble(99, fatConsuFinal.getContribucionTurismo7());
            pst.setDouble(100, fatConsuFinal.getImpuestoEspecifico());
            pst.setDouble(101, fatConsuFinal.getCesc());
            pst.setString(102, fatConsuFinal.getCampo1());
            pst.setString(103, fatConsuFinal.getCampo3());
            pst.setString(104, fatConsuFinal.getCampo2());
            pst.setString(105, fatConsuFinal.getCampo4());
            pst.setString(106, fatConsuFinal.getCampoExtFE());
            pst.setString(107, fatConsuFinal.getTipoItemExpor());
            pst.setString(108, fatConsuFinal.getCodSucE());
            pst.setString(109, fatConsuFinal.getEmailE());
            pst.setString(110, fatConsuFinal.getCodPais());
            pst.setString(111, fatConsuFinal.getObservacionesDte());
            pst.setString(112, fatConsuFinal.getNombrePais());
            pst.setString(113, fatConsuFinal.getFechaHoraGeneracion());
            pst.setString(114, fatConsuFinal.getTipoPersona());
            pst.setString(115, fatConsuFinal.getNumControl());
            pst.setString(116, fatConsuFinal.getCodGeneracion());
            pst.setString(117, fatConsuFinal.getTelsucE());
            pst.setString(118, fatConsuFinal.getSelloGeneracion());
            pst.setString(119, fatConsuFinal.getFormatodocumento());
            pst.setString(120, fatConsuFinal.getResolucion());
            pst.setString(121, fatConsuFinal.getResInicio());
            pst.setString(122, fatConsuFinal.getResFin());
            pst.setString(123, fatConsuFinal.getResFecha());
            pst.setString(124, fatConsuFinal.getSerie());
            pst.setString(125, fatConsuFinal.getOtrosDocIdent());
            pst.setString(126, fatConsuFinal.getOtrosDocDescri());
            pst.setString(127, fatConsuFinal.getVentCterNit());
            pst.setString(128, fatConsuFinal.getVentCterNombre());
            pst.setString(129, fatConsuFinal.getDocRelTipo());
            pst.setString(130, fatConsuFinal.getDocRelNum());
            pst.setString(131, fatConsuFinal.getDocRelFecha());
            pst.setString(132, fatConsuFinal.getFormaPago());
            pst.setString(133, fatConsuFinal.getPlazo());
            pst.setString(134, fatConsuFinal.getNomConductor());
            pst.setString(135, fatConsuFinal.getNumIdenConductor());
            pst.setString(136, fatConsuFinal.getModTransp());
            pst.setString(137, fatConsuFinal.getNumIdTransp());
            pst.setString(138, fatConsuFinal.getResponsableEmisor());
            pst.setString(139, fatConsuFinal.getNumDocEmisor());
            pst.setString(140, fatConsuFinal.getResponsableReceptor());
            pst.setString(141, fatConsuFinal.getNumDocReceptor());
            pst.setString(142, fatConsuFinal.getMostrarTributo());
            pst.setString(143, fatConsuFinal.getNumeroControl());
            pst.setString(144, fatConsuFinal.getCodigoGeneracion());
            pst.setString(145, fatConsuFinal.getMotivoContin());
            pst.setString(146, fatConsuFinal.getNombreComercialCl());
            pst.setString(147, fatConsuFinal.getCodContingencia());
            pst.setString(148, fatConsuFinal.getModeloFacturacion());
            pst.setString(149, fatConsuFinal.getTipoTransmisión());
            pst.setString(150, fatConsuFinal.getfInicioContin());
            pst.setString(151, fatConsuFinal.getfFinContin());
            pst.setString(152, fatConsuFinal.getHoraIniContin());
            pst.setString(153, fatConsuFinal.getHoraFinContin());
            pst.executeUpdate(); 

        } catch (Exception e) {
            throw e;
        } finally {
            this.desconectar();
        }
    }
    public void modificarEstadoFacturaConsumidorFinal(int id) throws Exception {
        try {
            this.conectar();
            String sql = "UPDATE faturaConsumidorFinal SET estado = 1  WHERE  idfaturaConsumidorFinal = ?;";
            PreparedStatement pst = this.getCon().prepareStatement(sql);
            pst.setInt(1, id);
            pst.executeUpdate();

        } catch (Exception e) {
            throw e;
        } finally {
            this.desconectar();
        }
    }
}
