/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.generacionExcel;

import com.dao.DaoCreditoFiscal;
import com.dao.DaoFaturaConsumidorFinal;
import com.modelo.creditoFiscal;
import com.modelo.faturaConsumidorFinal;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

/**
 *
 * @author josue
 */
public class CargarExcel {

    DaoCreditoFiscal daoCreditoFiscal = new DaoCreditoFiscal();
    DaoFaturaConsumidorFinal daoFaturaConsumidorFinal = new DaoFaturaConsumidorFinal();

    public void cargarExcel(String archivo) throws FileNotFoundException, IOException {

        InputStream inp = new FileInputStream(archivo);
        Workbook wb = WorkbookFactory.create(inp);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Sheet sheet = wb.getSheetAt(0);
        int numeroFilas = sheet.getLastRowNum();
        for (int i = 3; i <= numeroFilas; i++) {
            Row fila = sheet.getRow(i);
            if (fila == null) {
                continue;
            }
            try {
                // Crear objeto con los datos de la fila
                creditoFiscal fiscal = new creditoFiscal();
                fiscal.setNit(fila.getCell(0).getStringCellValue());
                fiscal.setNrc(fila.getCell(1).getStringCellValue());
                fiscal.setIdDepartamentoEmisor(Double.valueOf(fila.getCell(2).getNumericCellValue()).intValue());
                fiscal.setIdMunicipioEmisor(Double.valueOf(fila.getCell(3).getNumericCellValue()).intValue());
                fiscal.setDireccionEmisor(fila.getCell(4).getStringCellValue());
                Date date = fila.getCell(5).getDateCellValue();
                fiscal.setFechaEnvio(dateFormat.format(date));
                date = fila.getCell(6).getDateCellValue();
                fiscal.setFechaEmision(dateFormat.format(date));
                fiscal.setTerminal(fila.getCell(7).getStringCellValue());
                fiscal.setNumFactura(Double.valueOf(fila.getCell(8).getNumericCellValue()).intValue());
                fiscal.setCorrelativoInterno(Double.valueOf(fila.getCell(9).getNumericCellValue()).intValue());
                fiscal.setNumeroTransaccion(Double.valueOf(fila.getCell(10).getNumericCellValue()).intValue());
                fiscal.setCodigoUsuario(Double.valueOf(fila.getCell(11).getNumericCellValue()).intValue());
                fiscal.setNombreUsuario(fila.getCell(12).getStringCellValue());
                fiscal.setCorreoUsuario(fila.getCell(13).getStringCellValue());
                fiscal.setCajaSuc(fila.getCell(14).getStringCellValue());
                fiscal.setTipoDocumento(fila.getCell(15).getStringCellValue());
                fiscal.setPdv(fila.getCell(16).getStringCellValue());
                fiscal.setNitCliente(fila.getCell(17).getStringCellValue());
                fiscal.setDuiCliente(fila.getCell(18).getStringCellValue());
                fiscal.setNrcCliente(fila.getCell(19).getStringCellValue());
                fiscal.setCodigoCliente(Double.valueOf(fila.getCell(20).getNumericCellValue()).intValue());
                fiscal.setNombreCliente(fila.getCell(21).getStringCellValue());
                fiscal.setDireccionCliente(fila.getCell(22).getStringCellValue());
                fiscal.setDepartamento(fila.getCell(23).getStringCellValue());
                fiscal.setMunicipio(fila.getCell(24).getStringCellValue());
                fiscal.setTelefono(String.valueOf(fila.getCell(26).getNumericCellValue()));
                fiscal.setEmail(fila.getCell(27).getStringCellValue());
                fiscal.setSms(String.valueOf(fila.getCell(28).getNumericCellValue()));
                fiscal.setWhatsapp(String.valueOf(fila.getCell(29).getNumericCellValue()));
                fiscal.setIdDepartamentoReceptor(Double.valueOf(fila.getCell(30).getNumericCellValue()).intValue());
                fiscal.setIdMunicipioReceptor(Double.valueOf(fila.getCell(31).getNumericCellValue()).intValue());
                fiscal.setCodigoActividadEconomica(Double.valueOf(fila.getCell(32).getNumericCellValue()).intValue());
                fiscal.setTipoCatContribuyente(fila.getCell(33).getStringCellValue());
                fiscal.setGiro(fila.getCell(34).getStringCellValue());
                fiscal.setCodicionPago(Double.valueOf(fila.getCell(35).getNumericCellValue()).intValue());
                fiscal.setCCFAnterior(fila.getCell(36).getStringCellValue());
                fiscal.setVtaACuentaDe(fila.getCell(37).getStringCellValue());
                fiscal.setNotaRemision(fila.getCell(38).getStringCellValue());
                fiscal.setNoFecha(fila.getCell(39).getStringCellValue());
                fiscal.setSaldoCapital(fila.getCell(40).getNumericCellValue());
                fiscal.setDescripcion(fila.getCell(41).getStringCellValue());
                fiscal.setPrecioUnitario(fila.getCell(42).getNumericCellValue());
                fiscal.setVentasNoSujetas(fila.getCell(43).getNumericCellValue());
                fiscal.setIvaItem(fila.getCell(44).getNumericCellValue());
                fiscal.setDelAl(fila.getCell(45).getNumericCellValue());
                fiscal.setExportaciones(Double.valueOf(fila.getCell(46).getNumericCellValue()).intValue());
                fiscal.setNumDocRel(Double.valueOf(fila.getCell(47).getNumericCellValue()).intValue());
                fiscal.setCodTributo(Double.valueOf(fila.getCell(48).getNumericCellValue()).intValue());
                fiscal.setTributos(Double.valueOf(fila.getCell(49).getNumericCellValue()).intValue());
                fiscal.setUniMedidaCodigo(Double.valueOf(fila.getCell(50).getNumericCellValue()).intValue());
                fiscal.setVentasExentas(fila.getCell(51).getNumericCellValue());
                fiscal.setFecha(fila.getCell(52).getStringCellValue());
                fiscal.setTipoItem(Double.valueOf(fila.getCell(53).getNumericCellValue()).intValue());
                fiscal.setTipoDteRel(Double.valueOf(fila.getCell(54).getNumericCellValue()).intValue());
                fiscal.setCodigoRetencionMH(Double.valueOf(fila.getCell(55).getNumericCellValue()).intValue());
                fiscal.setCantidad(Double.valueOf(fila.getCell(56).getNumericCellValue()).intValue());
                fiscal.setVentasGravadas(Double.valueOf(fila.getCell(57).getNumericCellValue()).intValue());
                fiscal.setIvaRetenido(fila.getCell(58).getNumericCellValue());
                fiscal.setDescuento(fila.getCell(59).getNumericCellValue());
                fiscal.setDescuentoItem(Double.valueOf(fila.getCell(60).getNumericCellValue()).intValue());
                fiscal.setOtroMonNoAfec(Double.valueOf(fila.getCell(61).getNumericCellValue()).intValue());
                fiscal.setMontoLetras(fila.getCell(62).getStringCellValue());
                fiscal.setSumas(fila.getCell(63).getNumericCellValue());
                fiscal.setSubTotalVentasExentas(fila.getCell(64).getNumericCellValue());
                fiscal.setSubTotalVentasNoSujetas(fila.getCell(65).getNumericCellValue());
                fiscal.setSubTotalVentasGravadas(fila.getCell(66).getNumericCellValue());
                fiscal.setVentasGravada(fila.getCell(67).getNumericCellValue());
                fiscal.setIva(fila.getCell(68).getNumericCellValue());
                fiscal.setRenta(fila.getCell(69).getNumericCellValue());
                fiscal.setImpuesto(fila.getCell(70).getNumericCellValue());
                fiscal.setVentasExenta(fila.getCell(71).getNumericCellValue());
                fiscal.setVentasNoSujeta(fila.getCell(72).getNumericCellValue());
                fiscal.setTotalExportaciones(Double.valueOf(fila.getCell(73).getNumericCellValue()).intValue());
                fiscal.setCodigoTributos(Double.valueOf(fila.getCell(74).getNumericCellValue()).intValue());
                fiscal.setDescripcionTributo(fila.getCell(75).getStringCellValue());
                fiscal.setValorTributo(fila.getCell(76).getNumericCellValue());
                fiscal.setDescuentos(fila.getCell(77).getNumericCellValue());
                fiscal.setAbonos(fila.getCell(78).getNumericCellValue());
                fiscal.setCantidadTotal(Double.valueOf(fila.getCell(79).getNumericCellValue()).intValue());
                fiscal.setVentaTotal(fila.getCell(80).getNumericCellValue());
                fiscal.setVentasGravadas13(fila.getCell(81).getNumericCellValue());
                fiscal.setVentasGravadas0(fila.getCell(82).getNumericCellValue());
                fiscal.setVentasNoGravadas(fila.getCell(83).getNumericCellValue());
                fiscal.setIvaPercibido1(fila.getCell(84).getNumericCellValue());
                fiscal.setIvaPercibido2(fila.getCell(85).getNumericCellValue());
                fiscal.setIvaRetenido1(fila.getCell(86).getNumericCellValue());
                fiscal.setIvaRetenido13(fila.getCell(87).getNumericCellValue());
                fiscal.setMontGDescVentNoSujetas(fila.getCell(88).getNumericCellValue());
                fiscal.setMontGDescVentExentas(fila.getCell(89).getNumericCellValue());
                fiscal.setMontGDescVentGrav(fila.getCell(90).getNumericCellValue());
                fiscal.setTotOtroMonNoAfec(fila.getCell(91).getNumericCellValue());
                fiscal.setTotalAPagar(fila.getCell(92).getNumericCellValue());
                fiscal.setSeguro(fila.getCell(93).getNumericCellValue());
                fiscal.setFlete(fila.getCell(94).getNumericCellValue());
                fiscal.setContribucionSeguridad(fila.getCell(95).getNumericCellValue());
                fiscal.setFovial(fila.getCell(96).getNumericCellValue());
                fiscal.setCotrans(fila.getCell(97).getNumericCellValue());
                fiscal.setContribucionTurismo5(fila.getCell(98).getNumericCellValue());
                fiscal.setContribucionTurismo7(fila.getCell(99).getNumericCellValue());
                fiscal.setImpuestoEspecifico(fila.getCell(100).getNumericCellValue());
                fiscal.setCesc(fila.getCell(101).getNumericCellValue());
                fiscal.setCampo1(fila.getCell(102).getStringCellValue());
                fiscal.setCampo3(fila.getCell(103).getStringCellValue());
                fiscal.setCampo2(fila.getCell(104).getStringCellValue());
                fiscal.setCampo4(fila.getCell(105).getStringCellValue());
                fiscal.setCampoExtFE(fila.getCell(106).getStringCellValue());
                fiscal.setTipoItemExpor(fila.getCell(107).getStringCellValue());
                fiscal.setCodSucE(fila.getCell(108).getStringCellValue());
                fiscal.setEmailE(fila.getCell(109).getStringCellValue());
                fiscal.setCodPais(fila.getCell(110).getStringCellValue());
                fiscal.setObservacionesDte(fila.getCell(111).getStringCellValue());
                fiscal.setNombrePais(fila.getCell(112).getStringCellValue());
                fiscal.setFechaHoraGeneracion(fila.getCell(113).getStringCellValue());
                fiscal.setTipoPersona(fila.getCell(114).getStringCellValue());
                fiscal.setNumControl(fila.getCell(115).getStringCellValue());
                fiscal.setCodGeneracion(fila.getCell(116).getStringCellValue());
                fiscal.setTelsucE(fila.getCell(117).getStringCellValue());
                fiscal.setSelloGeneracion(fila.getCell(118).getStringCellValue());
                fiscal.setFormatodocumento(fila.getCell(119).getStringCellValue());
                fiscal.setResolucion(fila.getCell(120).getStringCellValue());
                fiscal.setResInicio(fila.getCell(121).getStringCellValue());
                fiscal.setResFin(fila.getCell(122).getStringCellValue());
                fiscal.setResFecha(fila.getCell(123).getStringCellValue());
                fiscal.setSerie(fila.getCell(124).getStringCellValue());
                fiscal.setOtrosDocIdent(fila.getCell(125).getStringCellValue());
                fiscal.setOtrosDocDescri(fila.getCell(126).getStringCellValue());
                fiscal.setVentCterNit(fila.getCell(127).getStringCellValue());
                fiscal.setVentCterNombre(fila.getCell(128).getStringCellValue());
                fiscal.setDocRelTipo(fila.getCell(129).getStringCellValue());
                fiscal.setDocRelNum(fila.getCell(130).getStringCellValue());
                fiscal.setDocRelFecha(fila.getCell(131).getStringCellValue());
                fiscal.setFormaPago(fila.getCell(132).getStringCellValue());
                fiscal.setPlazo(fila.getCell(133).getStringCellValue());
                fiscal.setNomConductor(fila.getCell(134).getStringCellValue());
                fiscal.setNumIdenConductor(fila.getCell(135).getStringCellValue());
                fiscal.setModTransp(fila.getCell(136).getStringCellValue());
                fiscal.setNumIdTransp(fila.getCell(137).getStringCellValue());
                fiscal.setResponsableEmisor(fila.getCell(138).getStringCellValue());
                fiscal.setNumDocEmisor(fila.getCell(139).getStringCellValue());
                fiscal.setResponsableReceptor(fila.getCell(140).getStringCellValue());
                fiscal.setNumDocReceptor(fila.getCell(141).getStringCellValue());
                fiscal.setMostrarTributo(fila.getCell(142).getStringCellValue());
                fiscal.setNumeroControl(fila.getCell(143).getStringCellValue());
                fiscal.setCodigoGeneracion(fila.getCell(144).getStringCellValue());
                fiscal.setMotivoContin(fila.getCell(145).getStringCellValue());
                fiscal.setNombreComercialCl(fila.getCell(146).getStringCellValue());
                fiscal.setCodContingencia(fila.getCell(147).getStringCellValue());
                fiscal.setModeloFacturacion(fila.getCell(148).getStringCellValue());
                fiscal.setTipoTransmision(fila.getCell(149).getStringCellValue());
                fiscal.setfInicioContin(fila.getCell(150).getStringCellValue());
                fiscal.setfFinContin(fila.getCell(151).getStringCellValue());
                fiscal.setHoraIniContin(fila.getCell(152).getStringCellValue());
                fiscal.setHoraFinContin(fila.getCell(153).getStringCellValue());
                daoCreditoFiscal.insertCreditoFiscal(fiscal);
            } catch (Exception e) {

            }
        }

        Sheet sheet1 = wb.getSheetAt(1);
        int numeroFilas1 = sheet1.getLastRowNum();
        Row fila = sheet1.getRow(3);

        try {
            faturaConsumidorFinal fatConsFinal = new faturaConsumidorFinal();

            fatConsFinal.setNit(fila.getCell(0).getStringCellValue());
            fatConsFinal.setNrc(fila.getCell(1).getStringCellValue());
            fatConsFinal.setIdDepartamentoEmisor(Double.valueOf(fila.getCell(2).getNumericCellValue()).intValue());
            fatConsFinal.setIdMunicipioEmisor(Double.valueOf(fila.getCell(3).getNumericCellValue()).intValue());
            fatConsFinal.setDireccionEmisor(fila.getCell(4).getStringCellValue());
            Date date = fila.getCell(5).getDateCellValue();
            fatConsFinal.setFechaEnvio(dateFormat.format(date));
            date = fila.getCell(6).getDateCellValue();
            fatConsFinal.setFechaEmision(dateFormat.format(date));
            fatConsFinal.setTerminal(fila.getCell(7).getStringCellValue());
            fatConsFinal.setNumFactura(Double.valueOf(fila.getCell(8).getNumericCellValue()).intValue());
            fatConsFinal.setCorrelativoInterno(Double.valueOf(fila.getCell(9).getNumericCellValue()).intValue());
            fatConsFinal.setNumeroTransaccion(Double.valueOf(fila.getCell(10).getNumericCellValue()).intValue());
            fatConsFinal.setCodigoUsuario(Double.valueOf(fila.getCell(11).getNumericCellValue()).intValue());
            fatConsFinal.setNombreUsuario(fila.getCell(12).getStringCellValue());
            fatConsFinal.setCorreoUsuario(fila.getCell(13).getStringCellValue());
            fatConsFinal.setCajaSuc(fila.getCell(14).getStringCellValue());
            fatConsFinal.setTipoDocumento(fila.getCell(15).getStringCellValue());
            fatConsFinal.setPdv(fila.getCell(16).getStringCellValue());
            fatConsFinal.setNitCliente(String.valueOf((int) fila.getCell(17).getNumericCellValue()));
            fatConsFinal.setDuiCliente(fila.getCell(18).getStringCellValue());
            fatConsFinal.setNrcCliente(String.valueOf((int) fila.getCell(19).getNumericCellValue()));
            fatConsFinal.setCodigoCliente(Double.valueOf(fila.getCell(20).getNumericCellValue()).intValue());
            fatConsFinal.setNombreCliente(fila.getCell(21).getStringCellValue());
            fatConsFinal.setDireccionCliente(fila.getCell(22).getStringCellValue());
            fatConsFinal.setDepartamento(fila.getCell(23).getStringCellValue());
            fatConsFinal.setMunicipio(fila.getCell(24).getStringCellValue());
            fatConsFinal.setTelefono(String.valueOf(fila.getCell(26).getNumericCellValue()));
            fatConsFinal.setEmail(fila.getCell(27).getStringCellValue());
            fatConsFinal.setSms(String.valueOf(fila.getCell(28).getNumericCellValue()));
            fatConsFinal.setWhatsapp(String.valueOf(fila.getCell(29).getNumericCellValue()));
            fatConsFinal.setIdDepartamentoReceptor(Double.valueOf(fila.getCell(30).getNumericCellValue()).intValue());
            fatConsFinal.setIdMunicipioReceptor(Double.valueOf(fila.getCell(31).getNumericCellValue()).intValue());
            fatConsFinal.setCodigoActividadEconomica(Double.valueOf(fila.getCell(32).getNumericCellValue()).intValue());
            fatConsFinal.setTipoCatContribuyente(fila.getCell(33).getStringCellValue());
            fatConsFinal.setGiro(fila.getCell(34).getStringCellValue());
            fatConsFinal.setCodicionPago(Double.valueOf(fila.getCell(35).getNumericCellValue()).intValue());
            fatConsFinal.setCCFAnterior(fila.getCell(36).getStringCellValue());
            fatConsFinal.setVtaACuentaDe(fila.getCell(37).getStringCellValue());
            fatConsFinal.setNotaRemision(fila.getCell(38).getStringCellValue());
            fatConsFinal.setNoFecha(fila.getCell(39).getStringCellValue());
            fatConsFinal.setSaldoCapital(fila.getCell(40).getNumericCellValue());
            fatConsFinal.setDescripcion(fila.getCell(41).getStringCellValue());
            fatConsFinal.setPrecioUnitario(fila.getCell(42).getNumericCellValue());
            fatConsFinal.setVentasNoSujetas(fila.getCell(43).getNumericCellValue());
            fatConsFinal.setIvaItem(fila.getCell(44).getNumericCellValue());
            fatConsFinal.setDelAl(fila.getCell(45).getNumericCellValue());
            fatConsFinal.setExportaciones(Double.valueOf(fila.getCell(46).getNumericCellValue()).intValue());
            fatConsFinal.setNumDocRel(Double.valueOf(fila.getCell(47).getNumericCellValue()).intValue());
            fatConsFinal.setCodTributo(Double.valueOf(fila.getCell(48).getNumericCellValue()).intValue());
            fatConsFinal.setTributos(Double.valueOf(fila.getCell(49).getNumericCellValue()).intValue());
            fatConsFinal.setUniMedidaCodigo(Double.valueOf(fila.getCell(50).getNumericCellValue()).intValue());
            fatConsFinal.setVentasExentas(fila.getCell(51).getNumericCellValue());
            fatConsFinal.setFecha(fila.getCell(52).getStringCellValue());
            fatConsFinal.setTipoItem(Double.valueOf(fila.getCell(53).getNumericCellValue()).intValue());
            fatConsFinal.setTipoDteRel(Double.valueOf(fila.getCell(54).getNumericCellValue()).intValue());
            fatConsFinal.setCodigoRetencionMH(Double.valueOf(fila.getCell(55).getNumericCellValue()).intValue());
            fatConsFinal.setCantidad(Double.valueOf(fila.getCell(56).getNumericCellValue()).intValue());
            fatConsFinal.setVentasGravadas(Double.valueOf(fila.getCell(57).getNumericCellValue()).intValue());
            fatConsFinal.setIvaRetenido(fila.getCell(58).getNumericCellValue());
            fatConsFinal.setDescuento(fila.getCell(59).getNumericCellValue());
            fatConsFinal.setDescuentoItem(Double.valueOf(fila.getCell(60).getNumericCellValue()).intValue());
            fatConsFinal.setOtroMonNoAfec(Double.valueOf(fila.getCell(61).getNumericCellValue()).intValue());
            fatConsFinal.setMontoLetras(fila.getCell(62).getStringCellValue());
            fatConsFinal.setSumas(fila.getCell(63).getNumericCellValue());
            fatConsFinal.setSubTotalVentasExentas(fila.getCell(64).getNumericCellValue());
            fatConsFinal.setSubTotalVentasNoSujetas(fila.getCell(65).getNumericCellValue());
            fatConsFinal.setSubTotalVentasGravadas(fila.getCell(66).getNumericCellValue());
            fatConsFinal.setVentasGravada(fila.getCell(67).getNumericCellValue());
            fatConsFinal.setIva(fila.getCell(68).getNumericCellValue());
            fatConsFinal.setRenta(fila.getCell(69).getNumericCellValue());
            fatConsFinal.setImpuesto(fila.getCell(70).getNumericCellValue());
            fatConsFinal.setVentasExenta(fila.getCell(71).getNumericCellValue());
            fatConsFinal.setVentasNoSujeta(fila.getCell(72).getNumericCellValue());
            fatConsFinal.setCodigoTributo(fila.getCell(73).getNumericCellValue());
            fatConsFinal.setCodigoTributos(Double.valueOf(fila.getCell(74).getNumericCellValue()).intValue());
            fatConsFinal.setDescripcionTributo(String.valueOf((int) fila.getCell(75).getNumericCellValue()));
            fatConsFinal.setValorTributo(fila.getCell(76).getNumericCellValue());
            fatConsFinal.setDescuentos(fila.getCell(77).getNumericCellValue());
            fatConsFinal.setAbonos(fila.getCell(78).getNumericCellValue());
            fatConsFinal.setCantidadTotal(Double.valueOf(fila.getCell(79).getNumericCellValue()).intValue());
            fatConsFinal.setVentaTotal(fila.getCell(80).getNumericCellValue());
            fatConsFinal.setVentasGravadas13(fila.getCell(81).getNumericCellValue());
            fatConsFinal.setVentasGravadas0(fila.getCell(82).getNumericCellValue());
            fatConsFinal.setVentasNoGravadas(fila.getCell(83).getNumericCellValue());
            fatConsFinal.setIvaPercibido1(fila.getCell(84).getNumericCellValue());
            fatConsFinal.setIvaPercibido2(fila.getCell(85).getNumericCellValue());
            fatConsFinal.setIvaRetenido1(fila.getCell(86).getNumericCellValue());
            fatConsFinal.setIvaRetenido13(fila.getCell(87).getNumericCellValue());
            fatConsFinal.setMontGDescVentNoSujetas(fila.getCell(88).getNumericCellValue());
            fatConsFinal.setMontGDescVentExentas(fila.getCell(89).getNumericCellValue());
            fatConsFinal.setMontGDescVentGrav(fila.getCell(90).getNumericCellValue());
            fatConsFinal.setTotOtroMonNoAfec(fila.getCell(91).getNumericCellValue());
            fatConsFinal.setTotalAPagar(fila.getCell(92).getNumericCellValue());
            fatConsFinal.setSeguro(fila.getCell(93).getNumericCellValue());
            fatConsFinal.setFlete(fila.getCell(94).getNumericCellValue());
            fatConsFinal.setContribucionSeguridad(fila.getCell(95).getNumericCellValue());
            fatConsFinal.setFovial(fila.getCell(96).getNumericCellValue());
            fatConsFinal.setCotrans(fila.getCell(97).getNumericCellValue());
            fatConsFinal.setContribucionTurismo5(fila.getCell(98).getNumericCellValue());
            fatConsFinal.setContribucionTurismo7(fila.getCell(99).getNumericCellValue());
            fatConsFinal.setImpuestoEspecifico(fila.getCell(100).getNumericCellValue());
            fatConsFinal.setCesc(fila.getCell(101).getNumericCellValue());
            fatConsFinal.setCampo1(fila.getCell(102).getStringCellValue());
            fatConsFinal.setCampo3(fila.getCell(103).getStringCellValue());
            fatConsFinal.setCampo2(fila.getCell(104).getStringCellValue());
            fatConsFinal.setCampo4(fila.getCell(105).getStringCellValue());
            fatConsFinal.setCampoExtFE(fila.getCell(106).getStringCellValue());
            fatConsFinal.setTipoItemExpor(fila.getCell(107).getStringCellValue());
            fatConsFinal.setCodSucE(fila.getCell(108).getStringCellValue());
            fatConsFinal.setEmailE(fila.getCell(109).getStringCellValue());
            fatConsFinal.setCodPais(fila.getCell(110).getStringCellValue());
            fatConsFinal.setObservacionesDte(fila.getCell(111).getStringCellValue());
            fatConsFinal.setNombrePais(fila.getCell(112).getStringCellValue());
            fatConsFinal.setFechaHoraGeneracion(fila.getCell(113).getStringCellValue());
            fatConsFinal.setTipoPersona(fila.getCell(114).getStringCellValue());
            fatConsFinal.setNumControl(fila.getCell(115).getStringCellValue());
            fatConsFinal.setCodGeneracion(fila.getCell(116).getStringCellValue());
            fatConsFinal.setTelsucE(fila.getCell(117).getStringCellValue());
            fatConsFinal.setSelloGeneracion(fila.getCell(118).getStringCellValue());
            fatConsFinal.setFormatodocumento(fila.getCell(119).getStringCellValue());
            fatConsFinal.setResolucion(fila.getCell(120).getStringCellValue());
            fatConsFinal.setResInicio(fila.getCell(121).getStringCellValue());
            fatConsFinal.setResFin(fila.getCell(122).getStringCellValue());
            fatConsFinal.setResFecha(fila.getCell(123).getStringCellValue());
            fatConsFinal.setSerie(fila.getCell(124).getStringCellValue());
            fatConsFinal.setOtrosDocIdent(fila.getCell(125).getStringCellValue());
            fatConsFinal.setOtrosDocDescri(fila.getCell(126).getStringCellValue());
            fatConsFinal.setVentCterNit(fila.getCell(127).getStringCellValue());
            fatConsFinal.setVentCterNombre(fila.getCell(128).getStringCellValue());
            fatConsFinal.setDocRelTipo(fila.getCell(129).getStringCellValue());
            fatConsFinal.setDocRelNum(fila.getCell(130).getStringCellValue());
            fatConsFinal.setDocRelFecha(fila.getCell(131).getStringCellValue());
            fatConsFinal.setFormaPago(fila.getCell(132).getStringCellValue());
            fatConsFinal.setPlazo(fila.getCell(133).getStringCellValue());
            fatConsFinal.setNomConductor(fila.getCell(134).getStringCellValue());
            fatConsFinal.setNumIdenConductor(fila.getCell(135).getStringCellValue());
            fatConsFinal.setModTransp(fila.getCell(136).getStringCellValue());
            fatConsFinal.setNumIdTransp(fila.getCell(137).getStringCellValue());
            fatConsFinal.setResponsableEmisor(fila.getCell(138).getStringCellValue());
            fatConsFinal.setNumDocEmisor(fila.getCell(139).getStringCellValue());
            fatConsFinal.setResponsableReceptor(fila.getCell(140).getStringCellValue());
            fatConsFinal.setNumDocReceptor(fila.getCell(141).getStringCellValue());
            fatConsFinal.setMostrarTributo(fila.getCell(142).getStringCellValue());
            fatConsFinal.setNumeroControl(fila.getCell(143).getStringCellValue());
            fatConsFinal.setCodigoGeneracion(fila.getCell(144).getStringCellValue());
            fatConsFinal.setMotivoContin(fila.getCell(145).getStringCellValue());
            fatConsFinal.setNombreComercialCl(fila.getCell(146).getStringCellValue());
            fatConsFinal.setCodContingencia(fila.getCell(147).getStringCellValue());
            fatConsFinal.setModeloFacturacion(fila.getCell(148).getStringCellValue());
            fatConsFinal.setTipoTransmisión(fila.getCell(149).getStringCellValue());
            fatConsFinal.setfInicioContin(fila.getCell(150).getStringCellValue());
            fatConsFinal.setfFinContin(fila.getCell(151).getStringCellValue());
            fatConsFinal.setHoraIniContin(fila.getCell(152).getStringCellValue());
            fatConsFinal.setHoraFinContin(fila.getCell(153).getStringCellValue());
            daoFaturaConsumidorFinal.insertFaturaConsumidorFinal(fatConsFinal);
        } catch (Exception e) {

        }

    }
}
